name: tierra_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.7.0
  firebase_auth: 3.1.3
  lottie: 1.2.1
  introduction_screen: 2.1.0
  google_fonts: 2.1.0
  google_sign_in: 5.1.1
  flutter_login_facebook: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/lottie/
  uses-material-design: true

